/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import java.awt.Color;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author AbasZ
 */
public class MainFrame extends javax.swing.JFrame {
    private String role;
    private String username;
    
    public MainFrame() {
        initComponents();
    }
    
    public MainFrame(String role, String username) {
        initComponents();
        this.role = role; 
        this.username = username; 
        
    }
    
    ImageIcon iconWarning = new javax.swing.ImageIcon(getClass().getResource("/Img/alarm.png"));

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Pmenu = new javax.swing.JPanel();
        pAwal = new javax.swing.JPanel();
        Name = new javax.swing.JLabel();
        pMenuIcon = new javax.swing.JLabel();
        pBeranda = new javax.swing.JPanel();
        IconBeranda = new javax.swing.JLabel();
        pDaftar = new javax.swing.JPanel();
        Icondaftar = new javax.swing.JLabel();
        pKuis = new javax.swing.JPanel();
        IconKuis = new javax.swing.JLabel();
        pLogOut = new javax.swing.JPanel();
        IconLogOut = new javax.swing.JLabel();
        pLine1 = new javax.swing.JPanel();
        pLine2 = new javax.swing.JPanel();
        pLine3 = new javax.swing.JPanel();
        pLine4 = new javax.swing.JPanel();
        pAlas = new javax.swing.JPanel();
        pHeader = new test.PanelRound();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        pIsiContent = new javax.swing.JPanel();
        pAlasIsi = new javax.swing.JPanel();
        pTmptGambar = new test.PanelRound();
        gambarYtama = new javax.swing.JLabel();
        pFooter = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Pmenu.setBackground(new java.awt.Color(255, 255, 255));
        Pmenu.setPreferredSize(new java.awt.Dimension(170, 525));

        pAwal.setBackground(new java.awt.Color(255, 255, 255));

        Name.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        Name.setForeground(new java.awt.Color(51, 51, 51));
        Name.setText("APERTA");

        pMenuIcon.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        pMenuIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/menu.png"))); // NOI18N
        pMenuIcon.setText("Menu");

        javax.swing.GroupLayout pAwalLayout = new javax.swing.GroupLayout(pAwal);
        pAwal.setLayout(pAwalLayout);
        pAwalLayout.setHorizontalGroup(
            pAwalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pAwalLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(pMenuIcon)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pAwalLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Name)
                .addGap(33, 33, 33))
        );
        pAwalLayout.setVerticalGroup(
            pAwalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pAwalLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(Name)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pMenuIcon, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                .addGap(12, 12, 12))
        );

        pBeranda.setBackground(new java.awt.Color(255, 255, 255));

        IconBeranda.setBackground(new java.awt.Color(255, 255, 255));
        IconBeranda.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        IconBeranda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/house.png"))); // NOI18N
        IconBeranda.setText("   Beranda");
        IconBeranda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                IconBerandaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                IconBerandaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                IconBerandaMouseExited(evt);
            }
        });

        javax.swing.GroupLayout pBerandaLayout = new javax.swing.GroupLayout(pBeranda);
        pBeranda.setLayout(pBerandaLayout);
        pBerandaLayout.setHorizontalGroup(
            pBerandaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pBerandaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(IconBeranda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        pBerandaLayout.setVerticalGroup(
            pBerandaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pBerandaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(IconBeranda)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pDaftar.setBackground(new java.awt.Color(255, 255, 255));
        pDaftar.setPreferredSize(new java.awt.Dimension(0, 36));

        Icondaftar.setBackground(java.awt.Color.lightGray);
        Icondaftar.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        Icondaftar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/edit.png"))); // NOI18N
        Icondaftar.setText("   Daftar Permainan");
        Icondaftar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                IcondaftarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                IcondaftarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                IcondaftarMouseExited(evt);
            }
        });

        javax.swing.GroupLayout pDaftarLayout = new javax.swing.GroupLayout(pDaftar);
        pDaftar.setLayout(pDaftarLayout);
        pDaftarLayout.setHorizontalGroup(
            pDaftarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pDaftarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Icondaftar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(5, 5, 5))
        );
        pDaftarLayout.setVerticalGroup(
            pDaftarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pDaftarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Icondaftar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pKuis.setBackground(new java.awt.Color(255, 255, 255));

        IconKuis.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        IconKuis.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/quiz.png"))); // NOI18N
        IconKuis.setText("   Kuis");
        IconKuis.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                IconKuisMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                IconKuisMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                IconKuisMouseExited(evt);
            }
        });

        javax.swing.GroupLayout pKuisLayout = new javax.swing.GroupLayout(pKuis);
        pKuis.setLayout(pKuisLayout);
        pKuisLayout.setHorizontalGroup(
            pKuisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pKuisLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(IconKuis, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pKuisLayout.setVerticalGroup(
            pKuisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pKuisLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(IconKuis)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pLogOut.setBackground(new java.awt.Color(255, 255, 255));

        IconLogOut.setBackground(java.awt.Color.lightGray);
        IconLogOut.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        IconLogOut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/logout.png"))); // NOI18N
        IconLogOut.setText("   Log Out");
        IconLogOut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                IconLogOutMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                IconLogOutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                IconLogOutMouseExited(evt);
            }
        });

        javax.swing.GroupLayout pLogOutLayout = new javax.swing.GroupLayout(pLogOut);
        pLogOut.setLayout(pLogOutLayout);
        pLogOutLayout.setHorizontalGroup(
            pLogOutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pLogOutLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(IconLogOut, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        pLogOutLayout.setVerticalGroup(
            pLogOutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pLogOutLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(IconLogOut)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pLine1.setBackground(new java.awt.Color(255, 255, 255));
        pLine1.setPreferredSize(new java.awt.Dimension(5, 0));

        javax.swing.GroupLayout pLine1Layout = new javax.swing.GroupLayout(pLine1);
        pLine1.setLayout(pLine1Layout);
        pLine1Layout.setHorizontalGroup(
            pLine1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );
        pLine1Layout.setVerticalGroup(
            pLine1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        pLine2.setBackground(new java.awt.Color(255, 255, 255));
        pLine2.setPreferredSize(new java.awt.Dimension(5, 100));

        javax.swing.GroupLayout pLine2Layout = new javax.swing.GroupLayout(pLine2);
        pLine2.setLayout(pLine2Layout);
        pLine2Layout.setHorizontalGroup(
            pLine2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        pLine2Layout.setVerticalGroup(
            pLine2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        pLine3.setBackground(new java.awt.Color(255, 255, 255));
        pLine3.setPreferredSize(new java.awt.Dimension(5, 0));

        javax.swing.GroupLayout pLine3Layout = new javax.swing.GroupLayout(pLine3);
        pLine3.setLayout(pLine3Layout);
        pLine3Layout.setHorizontalGroup(
            pLine3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        pLine3Layout.setVerticalGroup(
            pLine3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        pLine4.setBackground(new java.awt.Color(255, 255, 255));
        pLine4.setPreferredSize(new java.awt.Dimension(5, 0));

        javax.swing.GroupLayout pLine4Layout = new javax.swing.GroupLayout(pLine4);
        pLine4.setLayout(pLine4Layout);
        pLine4Layout.setHorizontalGroup(
            pLine4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );
        pLine4Layout.setVerticalGroup(
            pLine4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout PmenuLayout = new javax.swing.GroupLayout(Pmenu);
        Pmenu.setLayout(PmenuLayout);
        PmenuLayout.setHorizontalGroup(
            PmenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pAwal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PmenuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PmenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(PmenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(pLine1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(pLine2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(pLine3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(pLine4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(PmenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pLogOut, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pKuis, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pDaftar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
                    .addComponent(pBeranda, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        PmenuLayout.setVerticalGroup(
            PmenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PmenuLayout.createSequentialGroup()
                .addComponent(pAwal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(PmenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pLine1, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                    .addComponent(pBeranda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PmenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pLine2, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                    .addComponent(pDaftar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PmenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pLine3, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                    .addComponent(pKuis, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PmenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pLine4, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                    .addComponent(pLogOut, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 259, Short.MAX_VALUE))
        );

        getContentPane().add(Pmenu, java.awt.BorderLayout.LINE_START);

        pAlas.setBackground(new java.awt.Color(255, 255, 204));

        pHeader.setBackground(new java.awt.Color(0, 0, 153));
        pHeader.setRoundBottomLeft(50);
        pHeader.setRoundBottomRight(50);

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Aplikasi Informasi Permainan Tradisional");

        jLabel2.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Mari Lebih Mengenal Budaya Indonesia");

        javax.swing.GroupLayout pHeaderLayout = new javax.swing.GroupLayout(pHeader);
        pHeader.setLayout(pHeaderLayout);
        pHeaderLayout.setHorizontalGroup(
            pHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pHeaderLayout.createSequentialGroup()
                .addGap(113, 113, 113)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pHeaderLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(168, 168, 168))
        );
        pHeaderLayout.setVerticalGroup(
            pHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pHeaderLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        pIsiContent.setBackground(new java.awt.Color(255, 255, 204));
        pIsiContent.setLayout(new java.awt.BorderLayout());

        pAlasIsi.setBackground(new java.awt.Color(255, 255, 204));

        pTmptGambar.setBackground(new java.awt.Color(255, 255, 255));
        pTmptGambar.setRoundBottomLeft(60);
        pTmptGambar.setRoundBottomRight(60);
        pTmptGambar.setRoundTopLeft(60);
        pTmptGambar.setRoundTopRight(60);
        pTmptGambar.setLayout(new java.awt.BorderLayout());

        gambarYtama.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        gambarYtama.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/egrak.jpg"))); // NOI18N
        gambarYtama.setText("jLabel5");
        pTmptGambar.add(gambarYtama, java.awt.BorderLayout.CENTER);

        pFooter.setBackground(new java.awt.Color(0, 0, 153));

        jLabel3.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Copyright © by, Aperta2k24");

        javax.swing.GroupLayout pFooterLayout = new javax.swing.GroupLayout(pFooter);
        pFooter.setLayout(pFooterLayout);
        pFooterLayout.setHorizontalGroup(
            pFooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pFooterLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(263, 263, 263))
        );
        pFooterLayout.setVerticalGroup(
            pFooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pFooterLayout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addContainerGap())
        );

        javax.swing.GroupLayout pAlasIsiLayout = new javax.swing.GroupLayout(pAlasIsi);
        pAlasIsi.setLayout(pAlasIsiLayout);
        pAlasIsiLayout.setHorizontalGroup(
            pAlasIsiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pFooter, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pAlasIsiLayout.createSequentialGroup()
                .addContainerGap(127, Short.MAX_VALUE)
                .addComponent(pTmptGambar, javax.swing.GroupLayout.PREFERRED_SIZE, 477, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(115, 115, 115))
        );
        pAlasIsiLayout.setVerticalGroup(
            pAlasIsiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pAlasIsiLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(pTmptGambar, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(pFooter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pIsiContent.add(pAlasIsi, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout pAlasLayout = new javax.swing.GroupLayout(pAlas);
        pAlas.setLayout(pAlasLayout);
        pAlasLayout.setHorizontalGroup(
            pAlasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pHeader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pIsiContent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pAlasLayout.setVerticalGroup(
            pAlasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pAlasLayout.createSequentialGroup()
                .addComponent(pHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pIsiContent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(pAlas, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void IconBerandaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_IconBerandaMouseClicked
//         pBeranda.setBackground(Color.LIGHT_GRAY);
//         pLine1.setBackground(Color.BLUE);
         
         pIsiContent.removeAll();
         if ("admin".equals(role)) {
            pIsiContent.add(new MenuBerandaAdmin()); // Tampilkan beranda admin
         } else if ("user".equals(role)) {
            pIsiContent.add(new MenuBerandaUser()); // Tampilkan beranda user
         }
         pIsiContent.repaint();
         pIsiContent.revalidate();
    }//GEN-LAST:event_IconBerandaMouseClicked

    private void IcondaftarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_IcondaftarMouseClicked
//         pDaftar.setBackground(Color.LIGHT_GRAY);
//         pLine2.setBackground(Color.BLUE);
         
         pIsiContent.removeAll();
         if ("admin".equals(role)) {
            pIsiContent.add(new MenuDaftarPermainanAdmin()); // Tampilkan beranda admin
         } else if ("user".equals(role)) {
            pIsiContent.add(new MenuDaftarPermainanUser()); // Tampilkan beranda user
         }
         pIsiContent.repaint();
         pIsiContent.revalidate();
    }//GEN-LAST:event_IcondaftarMouseClicked

    private void IconBerandaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_IconBerandaMouseEntered
//        pBeranda.setBackground(Color.LIGHT_GRAY);
//        pLine1.setBackground(Color.BLUE);
    }//GEN-LAST:event_IconBerandaMouseEntered

    private void IconBerandaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_IconBerandaMouseExited
//        pBeranda.setBackground(Color.white);
//        pLine1.setBackground(Color.BLUE);
    }//GEN-LAST:event_IconBerandaMouseExited

    private void IcondaftarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_IcondaftarMouseEntered
//        pDaftar.setBackground(Color.LIGHT_GRAY);
//        pLine2.setBackground(Color.BLUE);
    }//GEN-LAST:event_IcondaftarMouseEntered

    private void IcondaftarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_IcondaftarMouseExited
//        pDaftar.setBackground(Color.white);
//        pLine2.setBackground(Color.BLUE);
    }//GEN-LAST:event_IcondaftarMouseExited

    private void IconKuisMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_IconKuisMouseClicked
//        pKuis.setBackground(Color.LIGHT_GRAY);
//        pLine3.setBackground(Color.BLUE);
        
        pIsiContent.removeAll();
        if ("admin".equals(role)) {
             pIsiContent.add(new MenuKuisAdmin()); // Tampilkan beranda admin
          } else if ("user".equals(role)) {
             pIsiContent.add(new MenuKuisUser()); // Tampilkan beranda user
          }
        pIsiContent.repaint();
        pIsiContent.revalidate();
    }//GEN-LAST:event_IconKuisMouseClicked

    private void IconKuisMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_IconKuisMouseEntered
//        pKuis.setBackground(Color.LIGHT_GRAY);
//        pLine3.setBackground(Color.BLUE);
    }//GEN-LAST:event_IconKuisMouseEntered

    private void IconKuisMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_IconKuisMouseExited
//        pKuis.setBackground(Color.white);
//        pLine3.setBackground(Color.BLUE);
    }//GEN-LAST:event_IconKuisMouseExited

    private void IconLogOutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_IconLogOutMouseClicked
        // TODO add your handling code here:
        int confirm = JOptionPane.showConfirmDialog(this, 
            "Apakah Anda yakin ingin logout?", 
            "Konfirmasi Logout", 
            JOptionPane.YES_NO_OPTION, 
            JOptionPane.QUESTION_MESSAGE,iconWarning );

        if (confirm == JOptionPane.YES_OPTION) {
            this.dispose(); 
            new FormLogin().setVisible(true); 
        }
    }//GEN-LAST:event_IconLogOutMouseClicked

    private void IconLogOutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_IconLogOutMouseEntered
//        pLogOut.setBackground(Color.LIGHT_GRAY);
//        pLine4.setBackground(Color.BLUE);
    }//GEN-LAST:event_IconLogOutMouseEntered

    private void IconLogOutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_IconLogOutMouseExited
//        pLogOut.setBackground(Color.LIGHT_GRAY);
//        pLine4.setBackground(Color.BLUE);
    }//GEN-LAST:event_IconLogOutMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel IconBeranda;
    private javax.swing.JLabel IconKuis;
    private javax.swing.JLabel IconLogOut;
    private javax.swing.JLabel Icondaftar;
    private javax.swing.JLabel Name;
    private javax.swing.JPanel Pmenu;
    private javax.swing.JLabel gambarYtama;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel pAlas;
    private javax.swing.JPanel pAlasIsi;
    private javax.swing.JPanel pAwal;
    private javax.swing.JPanel pBeranda;
    private javax.swing.JPanel pDaftar;
    private javax.swing.JPanel pFooter;
    private test.PanelRound pHeader;
    private javax.swing.JPanel pIsiContent;
    private javax.swing.JPanel pKuis;
    private javax.swing.JPanel pLine1;
    private javax.swing.JPanel pLine2;
    private javax.swing.JPanel pLine3;
    private javax.swing.JPanel pLine4;
    private javax.swing.JPanel pLogOut;
    private javax.swing.JLabel pMenuIcon;
    private test.PanelRound pTmptGambar;
    // End of variables declaration//GEN-END:variables
}
