/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View;

import java.awt.Image;
import java.sql.Connection;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author AbasZ
 */
public class MenuDaftarPermainanUser extends javax.swing.JPanel {

    /**
     * Creates new form MenuDaftarPermainanUser
     */
    public MenuDaftarPermainanUser() {
        initComponents();
        load_tableDaftarPermainan();
    }
    
    ImageIcon iconWarning = new javax.swing.ImageIcon(getClass().getResource("/Img/alarm.png"));
    ImageIcon iconInvalid = new javax.swing.ImageIcon(getClass().getResource("/Img/invalid.png"));

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pAlas = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TblPermainan = new javax.swing.JTable();
        pFooter = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtCariPermainan = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        BtnCariPermainanUser = new button.MyButton();
        lb_Gambar = new javax.swing.JLabel();
        txtNamaPermainan = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtDaerahAsal = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        taCaraBermain = new javax.swing.JTextArea();

        setLayout(new java.awt.BorderLayout());

        pAlas.setBackground(new java.awt.Color(255, 255, 204));

        TblPermainan.setBackground(new java.awt.Color(255, 255, 204));
        TblPermainan.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
        TblPermainan.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        TblPermainan.setForeground(new java.awt.Color(51, 51, 51));
        TblPermainan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "No", "Nama Permainan", "Daerah Asal", "Cara Bermain"
            }
        ));
        TblPermainan.setGridColor(new java.awt.Color(51, 51, 51));
        TblPermainan.setSelectionBackground(new java.awt.Color(255, 255, 255));
        TblPermainan.setSelectionForeground(new java.awt.Color(102, 102, 102));
        TblPermainan.setShowGrid(true);
        TblPermainan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TblPermainanMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TblPermainan);
        if (TblPermainan.getColumnModel().getColumnCount() > 0) {
            TblPermainan.getColumnModel().getColumn(0).setResizable(false);
            TblPermainan.getColumnModel().getColumn(0).setPreferredWidth(2);
        }

        pFooter.setBackground(new java.awt.Color(0, 0, 153));

        jLabel3.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Copyright © by, Aperta2k24");

        javax.swing.GroupLayout pFooterLayout = new javax.swing.GroupLayout(pFooter);
        pFooter.setLayout(pFooterLayout);
        pFooterLayout.setHorizontalGroup(
            pFooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pFooterLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(263, 263, 263))
        );
        pFooterLayout.setVerticalGroup(
            pFooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pFooterLayout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addContainerGap())
        );

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setText("Data Permainan Tradisional Indonesia");

        txtCariPermainan.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        txtCariPermainan.setForeground(new java.awt.Color(102, 102, 102));
        txtCariPermainan.setText("Berdasarkan Nama Permainan !");
        txtCariPermainan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtCariPermainanMouseClicked(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/search.png"))); // NOI18N

        BtnCariPermainanUser.setForeground(new java.awt.Color(102, 102, 102));
        BtnCariPermainanUser.setText("Cari");
        BtnCariPermainanUser.setBorderColor(new java.awt.Color(51, 51, 51));
        BtnCariPermainanUser.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        BtnCariPermainanUser.setRadius(15);
        BtnCariPermainanUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCariPermainanUserActionPerformed(evt);
            }
        });

        lb_Gambar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_Gambar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));

        txtNamaPermainan.setEditable(false);

        jLabel4.setText("Nama Permainan");

        jLabel5.setText("Daerah Asal");

        txtDaerahAsal.setEditable(false);

        jLabel6.setText("Cara Bermain");

        taCaraBermain.setEditable(false);
        taCaraBermain.setColumns(20);
        taCaraBermain.setRows(5);
        jScrollPane2.setViewportView(taCaraBermain);

        javax.swing.GroupLayout pAlasLayout = new javax.swing.GroupLayout(pAlas);
        pAlas.setLayout(pAlasLayout);
        pAlasLayout.setHorizontalGroup(
            pAlasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pAlasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addComponent(pFooter, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pAlasLayout.createSequentialGroup()
                .addGroup(pAlasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(pAlasLayout.createSequentialGroup()
                        .addGap(199, 199, 199)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtCariPermainan, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pAlasLayout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addGroup(pAlasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(36, 36, 36)
                        .addGroup(pAlasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNamaPermainan)
                            .addComponent(txtDaerahAsal)
                            .addComponent(jScrollPane2))))
                .addGap(18, 18, 18)
                .addGroup(pAlasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BtnCariPermainanUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb_Gambar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(148, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pAlasLayout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(196, 196, 196))
        );
        pAlasLayout.setVerticalGroup(
            pAlasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pAlasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pAlasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pAlasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtCariPermainan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(BtnCariPermainanUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel2))
                .addGroup(pAlasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pAlasLayout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addGroup(pAlasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNamaPermainan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGroup(pAlasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pAlasLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel5))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pAlasLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtDaerahAsal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(pAlasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(14, 14, 14))
                    .addGroup(pAlasLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(lb_Gambar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(pFooter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        add(pAlas, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void TblPermainanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TblPermainanMouseClicked
        // TODO add your handling code here:
        int row = TblPermainan.getSelectedRow(); // Mendapatkan baris yang diklik

        if (row != -1) {
            // Mengisi field berdasarkan tabel
            txtNamaPermainan.setText(TblPermainan.getValueAt(row, 1).toString()); 
            txtDaerahAsal.setText(TblPermainan.getValueAt(row, 2).toString()); 
            taCaraBermain.setText(TblPermainan.getValueAt(row, 3).toString()); 

            // Ambil gambar dari database berdasarkan id_permainan
            String namaPermainan = TblPermainan.getValueAt(row, 1).toString(); 
            loadGambar(namaPermainan);
        }
    }

    // Fungsi untuk mengambil gambar dari database
    private void loadGambar(String namaPermainan) {
        try {
            String sql = "SELECT gambar FROM tb_permainan WHERE nama_permainan = ?";
            java.sql.Connection conn = (Connection) Koneksi.getKoneksi();
            java.sql.PreparedStatement pst = conn.prepareStatement(sql);
            pst.setString(1, namaPermainan);

            java.sql.ResultSet rs = pst.executeQuery();
            if (rs.next()) {
                byte[] imgBytes = rs.getBytes("gambar");
                if (imgBytes != null) {
                    // Konversi byte array ke ImageIcon
                    ImageIcon imageIcon = new ImageIcon(imgBytes);

                    // Resize gambar agar sesuai JLabel
                    Image scaledImage = imageIcon.getImage().getScaledInstance(lb_Gambar.getWidth(), lb_Gambar.getHeight(), Image.SCALE_SMOOTH);
                    lb_Gambar.setIcon(new ImageIcon(scaledImage));
                } else {
                    // Kosongkan label jika tidak ada gambar
                    lb_Gambar.setIcon(null);
                    lb_Gambar.setText("Gambar tidak tersedia");
                }
            }
            rs.close();
            pst.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_TblPermainanMouseClicked

    private void txtCariPermainanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCariPermainanMouseClicked
        // TODO add your handling code here:
        txtCariPermainan.setText("");
    }//GEN-LAST:event_txtCariPermainanMouseClicked

    private void BtnCariPermainanUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCariPermainanUserActionPerformed
        // TODO add your handling code here:
        if (txtCariPermainan.getText().isEmpty()) {
        JOptionPane.showMessageDialog(this, "Masukkan nama permainan yang ingin dicari!", "Data Tidak Lengkap", JOptionPane.WARNING_MESSAGE, iconInvalid);
        return;
    }

        try {
            // Query SQL untuk mencari data berdasarkan nama (tidak peka huruf besar/kecil)
            String sql = "SELECT * FROM tb_permainan WHERE LOWER(nama_permainan) LIKE ?";
            java.sql.Connection conn = (Connection) Koneksi.getKoneksi();
            java.sql.PreparedStatement pst = conn.prepareStatement(sql);

            // Mengisi parameter query (mengubah input menjadi lowercase untuk pencocokan)
            pst.setString(1, "%" + txtCariPermainan.getText().toLowerCase() + "%");

            // Eksekusi query
            java.sql.ResultSet rs = pst.executeQuery();

            // Cek jika data ditemukan
            if (rs.next()) {
                // Menampilkan hasil pencarian ke field dan label gambar
                txtNamaPermainan.setText(rs.getString("nama_permainan"));
                txtDaerahAsal.setText(rs.getString("daerah_asal"));
                taCaraBermain.setText(rs.getString("cara_bermain"));

                // Menampilkan gambar
                byte[] img = rs.getBytes("gambar");
                if (img != null) {
                    ImageIcon imageIcon = new ImageIcon(img);
                    Image scaledImage = imageIcon.getImage().getScaledInstance(lb_Gambar.getWidth(), lb_Gambar.getHeight(), Image.SCALE_SMOOTH);
                    lb_Gambar.setIcon(new ImageIcon(scaledImage));
                } else {
                    lb_Gambar.setIcon(null); // Kosongkan jika tidak ada gambar
                    lb_Gambar.setText("Tidak ada gambar");
                }
            } else {
                // Jika data tidak ditemukan
                JOptionPane.showMessageDialog(this, "Data tidak ditemukan!", "Hasil Pencarian", JOptionPane.INFORMATION_MESSAGE, iconWarning);

                ResetTabelPermainan();
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_BtnCariPermainanUserActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private button.MyButton BtnCariPermainanUser;
    private javax.swing.JTable TblPermainan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lb_Gambar;
    private javax.swing.JPanel pAlas;
    private javax.swing.JPanel pFooter;
    private javax.swing.JTextArea taCaraBermain;
    private javax.swing.JTextField txtCariPermainan;
    private javax.swing.JTextField txtDaerahAsal;
    private javax.swing.JTextField txtNamaPermainan;
    // End of variables declaration//GEN-END:variables

    private void load_tableDaftarPermainan() {
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("No");
        model.addColumn("Nama Permainan");
        model.addColumn("Daerah Asal");
        model.addColumn("Cara Bermain");
        try {
            int no = 1;
            String sql = "SELECT nama_permainan, daerah_asal, cara_bermain FROM tb_permainan";
            java.sql.Connection conn = (Connection) Koneksi.getKoneksi();
            java.sql.Statement stm = conn.createStatement();
            java.sql.ResultSet res = stm.executeQuery(sql);
            while (res.next()){
                model.addRow(
                        new Object[]{
                            no++,
                            res.getString("nama_permainan"),
                            res.getString("daerah_asal"),
                            res.getString("cara_bermain"),
                        }
                );
            }
            TblPermainan.setModel(model);
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }
    
        private void ResetTabelPermainan() {
        txtNamaPermainan.setText("");
        txtDaerahAsal.setText("");
        taCaraBermain.setText("");
        lb_Gambar.setIcon(null);
        txtCariPermainan.setText("Berdasarkan Nama Permainan!");
    }
}
