/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View;

import java.awt.HeadlessException;
import java.io.IOException;
import java.sql.Connection;
import java.sql.SQLException;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author AbasZ
 */
public class MenuKuisAdmin extends javax.swing.JPanel {
    
    public MenuKuisAdmin() {
        initComponents();
        load_data_kuis();
    }
    
    ImageIcon iconInvalid = new javax.swing.ImageIcon(getClass().getResource("/Img/invalid.png"));
    ImageIcon iconSucces = new javax.swing.ImageIcon(getClass().getResource("/Img/berhasil.png"));
    ImageIcon iconWarning = new javax.swing.ImageIcon(getClass().getResource("/Img/alarm.png"));

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgSoal1 = new javax.swing.ButtonGroup();
        bgSoal2 = new javax.swing.ButtonGroup();
        bgSoal3 = new javax.swing.ButtonGroup();
        bgSoal4 = new javax.swing.ButtonGroup();
        bgSoal5 = new javax.swing.ButtonGroup();
        pAlas = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        tab1 = new test.PanelRound();
        pFooter = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        Pertanyaan1 = new javax.swing.JLabel();
        rb1A = new javax.swing.JRadioButton();
        rb1B = new javax.swing.JRadioButton();
        rb1C = new javax.swing.JRadioButton();
        rb1D = new javax.swing.JRadioButton();
        Pertanyaan2 = new javax.swing.JLabel();
        rb2A = new javax.swing.JRadioButton();
        rb2B = new javax.swing.JRadioButton();
        rb2C = new javax.swing.JRadioButton();
        rb2D = new javax.swing.JRadioButton();
        Pertanyaan3 = new javax.swing.JLabel();
        rb3A = new javax.swing.JRadioButton();
        rb3B = new javax.swing.JRadioButton();
        rb3C = new javax.swing.JRadioButton();
        rb3D = new javax.swing.JRadioButton();
        Pertanyaan4 = new javax.swing.JLabel();
        rb4A = new javax.swing.JRadioButton();
        rb4B = new javax.swing.JRadioButton();
        rb4C = new javax.swing.JRadioButton();
        rb4D = new javax.swing.JRadioButton();
        Pertanyaan5 = new javax.swing.JLabel();
        rb5A = new javax.swing.JRadioButton();
        rb5B = new javax.swing.JRadioButton();
        rb5C = new javax.swing.JRadioButton();
        rb5D = new javax.swing.JRadioButton();
        BtnKirimJawaban = new button.MyButton();
        BtnresetPermainan = new button.MyButton();
        tab2 = new test.PanelRound();
        pFooter1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        BtnDelete = new button.MyButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TblDataKuis = new javax.swing.JTable();

        setLayout(new java.awt.BorderLayout());

        pAlas.setBackground(new java.awt.Color(255, 255, 204));

        jTabbedPane1.setBackground(new java.awt.Color(0, 0, 153));
        jTabbedPane1.setForeground(new java.awt.Color(255, 255, 255));
        jTabbedPane1.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N

        tab1.setBackground(new java.awt.Color(255, 255, 204));

        pFooter.setBackground(new java.awt.Color(0, 0, 153));

        jLabel3.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Copyright © by, Aperta2k24");

        javax.swing.GroupLayout pFooterLayout = new javax.swing.GroupLayout(pFooter);
        pFooter.setLayout(pFooterLayout);
        pFooterLayout.setHorizontalGroup(
            pFooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pFooterLayout.createSequentialGroup()
                .addContainerGap(268, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(263, 263, 263))
        );
        pFooterLayout.setVerticalGroup(
            pFooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pFooterLayout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addContainerGap())
        );

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setText("Selamat Mengerjakan :)");

        Pertanyaan1.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        Pertanyaan1.setText("<html>\n 1. Dari mana asal permainan tradisional \"Congklak\"?<br>\n </html>");

        bgSoal1.add(rb1A);
        rb1A.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        rb1A.setText("Sumatra Utara");

        bgSoal1.add(rb1B);
        rb1B.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        rb1B.setText("Jawa barat");

        bgSoal1.add(rb1C);
        rb1C.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        rb1C.setText("Kalimantan");

        bgSoal1.add(rb1D);
        rb1D.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        rb1D.setText("Sulawesi utara");

        Pertanyaan2.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        Pertanyaan2.setText("<html>  2. Apa nama alat yang digunakan dalam permainan tradisional \"Gasing\"?  </html>");

        bgSoal2.add(rb2A);
        rb2A.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        rb2A.setText("Bola rotan");

        bgSoal2.add(rb2B);
        rb2B.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        rb2B.setText(" Kayu berputar");
        rb2B.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb2BActionPerformed(evt);
            }
        });

        bgSoal2.add(rb2C);
        rb2C.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        rb2C.setText("Kelereng");

        bgSoal2.add(rb2D);
        rb2D.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        rb2D.setText("Lidi panjang");

        Pertanyaan3.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        Pertanyaan3.setText("<html>  3. Dalam permainan \"Egrang\", apa yang digunakan untuk bermain?  </html>");

        bgSoal3.add(rb3A);
        rb3A.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        rb3A.setText("Batang bambu panjang");
        rb3A.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb3AActionPerformed(evt);
            }
        });

        bgSoal3.add(rb3B);
        rb3B.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        rb3B.setText(" Kayu bulat kecil");
        rb3B.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb3BActionPerformed(evt);
            }
        });

        bgSoal3.add(rb3C);
        rb3C.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        rb3C.setText(" Ban bekas");

        bgSoal3.add(rb3D);
        rb3D.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        rb3D.setText("Bola rotan");

        Pertanyaan4.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        Pertanyaan4.setText("<html>  4. Apa tujuan utama dari permainan \"Benteng\"?  </html>");

        bgSoal4.add(rb4A);
        rb4A.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        rb4A.setText("Mencuri bendera lawan");

        bgSoal4.add(rb4B);
        rb4B.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        rb4B.setText("Menangkap lawan di wilayah mereka");
        rb4B.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb4BActionPerformed(evt);
            }
        });

        bgSoal4.add(rb4C);
        rb4C.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        rb4C.setText("Menjaga benteng tim sendiri");

        bgSoal4.add(rb4D);
        rb4D.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        rb4D.setText("Menjatuhkan pemain lawan");

        Pertanyaan5.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        Pertanyaan5.setText("<html>  5 .\"Bakiak\" adalah permainan tradisional yang dimainkan secara...?  </html>");

        bgSoal5.add(rb5A);
        rb5A.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        rb5A.setText(" Individu");

        bgSoal5.add(rb5B);
        rb5B.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        rb5B.setText("Tim");
        rb5B.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb5BActionPerformed(evt);
            }
        });

        bgSoal5.add(rb5C);
        rb5C.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        rb5C.setText("Berpasangan");

        bgSoal5.add(rb5D);
        rb5D.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        rb5D.setText("Acak");

        BtnKirimJawaban.setForeground(new java.awt.Color(102, 102, 102));
        BtnKirimJawaban.setText("Kirim");
        BtnKirimJawaban.setBorderColor(new java.awt.Color(51, 51, 51));
        BtnKirimJawaban.setRadius(20);
        BtnKirimJawaban.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnKirimJawabanActionPerformed(evt);
            }
        });

        BtnresetPermainan.setForeground(new java.awt.Color(102, 102, 102));
        BtnresetPermainan.setText("Reset");
        BtnresetPermainan.setBorderColor(new java.awt.Color(51, 51, 51));
        BtnresetPermainan.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        BtnresetPermainan.setRadius(20);
        BtnresetPermainan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnresetPermainanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout tab1Layout = new javax.swing.GroupLayout(tab1);
        tab1.setLayout(tab1Layout);
        tab1Layout.setHorizontalGroup(
            tab1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pFooter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tab1Layout.createSequentialGroup()
                .addGroup(tab1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(tab1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(tab1Layout.createSequentialGroup()
                            .addContainerGap(20, Short.MAX_VALUE)
                            .addGroup(tab1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(rb4C)
                                .addComponent(rb4A))
                            .addGap(18, 18, 18)
                            .addGroup(tab1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(rb4B)
                                .addComponent(rb4D)))
                        .addGroup(tab1Layout.createSequentialGroup()
                            .addGap(12, 12, 12)
                            .addComponent(Pertanyaan4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(51, 51, 51)))
                    .addGroup(tab1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)))
                .addGap(277, 277, 277))
            .addGroup(tab1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(tab1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tab1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(rb5A)
                        .addGap(18, 18, 18)
                        .addComponent(rb5B)
                        .addGap(18, 18, 18)
                        .addComponent(rb5C)
                        .addGap(18, 18, 18)
                        .addComponent(rb5D)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BtnresetPermainan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(BtnKirimJawaban, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15))
                    .addGroup(tab1Layout.createSequentialGroup()
                        .addGroup(tab1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(tab1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(tab1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(tab1Layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addGroup(tab1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(rb3A)
                                            .addComponent(rb3C))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(tab1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(rb3B)
                                            .addComponent(rb3D)))
                                    .addGroup(tab1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(tab1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(tab1Layout.createSequentialGroup()
                                                .addGap(6, 6, 6)
                                                .addComponent(rb2A)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(rb2B)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(rb2C)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(rb2D))
                                            .addGroup(tab1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(Pertanyaan2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGroup(tab1Layout.createSequentialGroup()
                                                    .addComponent(rb1A)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(rb1B)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(rb1C)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(rb1D))))
                                        .addGroup(tab1Layout.createSequentialGroup()
                                            .addComponent(Pertanyaan3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(33, 33, 33))))
                                .addGroup(tab1Layout.createSequentialGroup()
                                    .addComponent(Pertanyaan1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(111, 111, 111)))
                            .addComponent(Pertanyaan5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        tab1Layout.setVerticalGroup(
            tab1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tab1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Pertanyaan1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tab1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rb1A)
                    .addComponent(rb1B)
                    .addComponent(rb1C)
                    .addComponent(rb1D))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Pertanyaan2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tab1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rb2A)
                    .addComponent(rb2B)
                    .addComponent(rb2C)
                    .addComponent(rb2D))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Pertanyaan3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tab1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rb3A)
                    .addComponent(rb3B))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tab1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rb3D)
                    .addComponent(rb3C))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Pertanyaan4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tab1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rb4A)
                    .addComponent(rb4B))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tab1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rb4C)
                    .addComponent(rb4D))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Pertanyaan5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tab1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rb5B)
                    .addComponent(rb5C)
                    .addComponent(rb5D)
                    .addComponent(rb5A)
                    .addComponent(BtnKirimJawaban, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnresetPermainan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addComponent(pFooter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jTabbedPane1.addTab("Kuis", tab1);

        tab2.setBackground(new java.awt.Color(255, 255, 204));
        tab2.setForeground(new java.awt.Color(255, 255, 204));

        pFooter1.setBackground(new java.awt.Color(0, 0, 153));

        jLabel4.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Copyright © by, Aperta2k24");

        javax.swing.GroupLayout pFooter1Layout = new javax.swing.GroupLayout(pFooter1);
        pFooter1.setLayout(pFooter1Layout);
        pFooter1Layout.setHorizontalGroup(
            pFooter1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pFooter1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(263, 263, 263))
        );
        pFooter1Layout.setVerticalGroup(
            pFooter1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pFooter1Layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addContainerGap())
        );

        jLabel6.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 102, 102));
        jLabel6.setText("Daftar Orang-Orang Cerdas");

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/profit.png"))); // NOI18N

        BtnDelete.setForeground(new java.awt.Color(102, 102, 102));
        BtnDelete.setText("Delete");
        BtnDelete.setBorderColor(new java.awt.Color(51, 51, 51));
        BtnDelete.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        BtnDelete.setRadius(20);
        BtnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnDeleteActionPerformed(evt);
            }
        });

        TblDataKuis.setBackground(new java.awt.Color(255, 255, 204));
        TblDataKuis.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        TblDataKuis.setForeground(new java.awt.Color(102, 102, 102));
        TblDataKuis.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "No", "Nama", "Skor"
            }
        ));
        TblDataKuis.setShowGrid(true);
        jScrollPane1.setViewportView(TblDataKuis);

        javax.swing.GroupLayout tab2Layout = new javax.swing.GroupLayout(tab2);
        tab2.setLayout(tab2Layout);
        tab2Layout.setHorizontalGroup(
            tab2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pFooter1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(tab2Layout.createSequentialGroup()
                .addGroup(tab2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(tab2Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel7))
                    .addGroup(tab2Layout.createSequentialGroup()
                        .addGap(122, 122, 122)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BtnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        tab2Layout.setVerticalGroup(
            tab2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tab2Layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addGroup(tab2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tab2Layout.createSequentialGroup()
                        .addComponent(BtnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tab2Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)))
                .addGroup(tab2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(20, 20, 20)
                .addComponent(pFooter1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jTabbedPane1.addTab("Tabel Kuis", tab2);

        javax.swing.GroupLayout pAlasLayout = new javax.swing.GroupLayout(pAlas);
        pAlas.setLayout(pAlasLayout);
        pAlasLayout.setHorizontalGroup(
            pAlasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        pAlasLayout.setVerticalGroup(
            pAlasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        add(pAlas, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void rb2BActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb2BActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rb2BActionPerformed

    private void rb3AActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb3AActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rb3AActionPerformed

    private void rb3BActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb3BActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rb3BActionPerformed

    private void rb4BActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb4BActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rb4BActionPerformed

    private void rb5BActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb5BActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rb5BActionPerformed

    private void BtnKirimJawabanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnKirimJawabanActionPerformed
        try {
            int skor = 0;

            // Pertanyaan 1: Sumatra Utara
            if (rb1A.isSelected()) {
                skor += 20;
            }

            // Pertanyaan 2: Kayu berputar
            if (rb2B.isSelected()) {
                skor += 20;
            }

            // Pertanyaan 3: Batang bambu panjang
            if (rb3A.isSelected()) {
                skor += 20;
            }

            // Pertanyaan 4: Menjaga benteng tim sendiri
            if (rb4C.isSelected()) {
                skor += 20;
            }

            // Pertanyaan 5: Tim
            if (rb5B.isSelected()) {
                skor += 20;
            }

            // Menampilkan skor dengan JOptionPane
            String message = "Skor Anda: " + skor;
            JOptionPane.showMessageDialog(this, message);

            // Meminta nama pengguna
            String nama = "";
            while (true) {
                nama = JOptionPane.showInputDialog(this, "Masukkan Nama Anda:");
                if (nama == null) {
                    JOptionPane.showMessageDialog(this,"Proses dibatalkan", "Gagal", JOptionPane.INFORMATION_MESSAGE,iconInvalid);
                    return;
                } else if (nama.trim().isEmpty()) {
                    JOptionPane.showMessageDialog(this,"Nama tidak boleh kosong", "Invalid", JOptionPane.INFORMATION_MESSAGE,iconInvalid);
                } else {
                    break;
                }
            }
            
             try {
                String sql = "INSERT INTO tb_data_quiz (nama, skor) VALUES (?, ?)";
                java.sql.Connection conn = (Connection) Koneksi.getKoneksi();
                java.sql.PreparedStatement pst = conn.prepareStatement(sql);
                pst.setString(1, nama);
                pst.setInt(2, skor);
                pst.executeUpdate();
                JOptionPane.showMessageDialog(this,"Data berhasil disimpan", "Success", JOptionPane.INFORMATION_MESSAGE, iconSucces);
                load_data_kuis();
            } catch (HeadlessException | SQLException ex) {
                ex.printStackTrace();
                JOptionPane.showMessageDialog(this,"Terjadi kesalahan saat menyimpan ke database", "Error", JOptionPane.ERROR_MESSAGE, iconWarning);
            }

            // Reset kuis
            resetQuiz();

        }catch(NumberFormatException ex){

        }
    }//GEN-LAST:event_BtnKirimJawabanActionPerformed

    private void BtnresetPermainanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnresetPermainanActionPerformed
        resetQuiz();
    }//GEN-LAST:event_BtnresetPermainanActionPerformed

    private void BtnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnDeleteActionPerformed
        // TODO add your handling code here:
        int selectedRow = TblDataKuis.getSelectedRow();
            if (selectedRow == -1) {
                JOptionPane.showMessageDialog(this, 
                        "Pilih data yang akan dihapus dari tabel!", 
                        "Peringatan", 
                        JOptionPane.WARNING_MESSAGE, iconWarning);
                return;
            }
            
        // Konfirmasi penghapusan
        int confirm = JOptionPane.showConfirmDialog(this, 
                "Apakah Anda yakin ingin menghapus data ini?", 
                "Konfirmasi Hapus Data", 
                JOptionPane.YES_NO_OPTION, 
                JOptionPane.WARNING_MESSAGE,iconWarning);

        if (confirm == JOptionPane.YES_OPTION) {
            try {
                String Nama = TblDataKuis.getValueAt(selectedRow, 1).toString();
                
                String sql;
                sql = "DELETE FROM tb_data_quiz WHERE nama = ?";
                java.sql.Connection conn = (Connection) Koneksi.getKoneksi();
                java.sql.PreparedStatement pst = conn.prepareStatement(sql);

                // Set parameter ID yang akan dihapus
                pst.setString(1, Nama);

                // Eksekusi query
                int rowsAffected = pst.executeUpdate();
                if (rowsAffected > 0) {
                    JOptionPane.showMessageDialog(this, "Data berhasil dihapus!", "Success", JOptionPane.INFORMATION_MESSAGE, iconSucces);
                    load_data_kuis();
                } else {
                    JOptionPane.showMessageDialog(this, "Data gagal dihapus. Pastikan ID valid!", "Error", JOptionPane.ERROR_MESSAGE, iconInvalid);
                }

            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Error: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_BtnDeleteActionPerformed

    private void resetQuiz() {
       bgSoal1.clearSelection();
       bgSoal2.clearSelection();
       bgSoal3.clearSelection();
       bgSoal4.clearSelection();
       bgSoal5.clearSelection();
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private button.MyButton BtnDelete;
    private button.MyButton BtnKirimJawaban;
    private button.MyButton BtnresetPermainan;
    private javax.swing.JLabel Pertanyaan1;
    private javax.swing.JLabel Pertanyaan2;
    private javax.swing.JLabel Pertanyaan3;
    private javax.swing.JLabel Pertanyaan4;
    private javax.swing.JLabel Pertanyaan5;
    private javax.swing.JTable TblDataKuis;
    private javax.swing.ButtonGroup bgSoal1;
    private javax.swing.ButtonGroup bgSoal2;
    private javax.swing.ButtonGroup bgSoal3;
    private javax.swing.ButtonGroup bgSoal4;
    private javax.swing.ButtonGroup bgSoal5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JPanel pAlas;
    private javax.swing.JPanel pFooter;
    private javax.swing.JPanel pFooter1;
    private javax.swing.JRadioButton rb1A;
    private javax.swing.JRadioButton rb1B;
    private javax.swing.JRadioButton rb1C;
    private javax.swing.JRadioButton rb1D;
    private javax.swing.JRadioButton rb2A;
    private javax.swing.JRadioButton rb2B;
    private javax.swing.JRadioButton rb2C;
    private javax.swing.JRadioButton rb2D;
    private javax.swing.JRadioButton rb3A;
    private javax.swing.JRadioButton rb3B;
    private javax.swing.JRadioButton rb3C;
    private javax.swing.JRadioButton rb3D;
    private javax.swing.JRadioButton rb4A;
    private javax.swing.JRadioButton rb4B;
    private javax.swing.JRadioButton rb4C;
    private javax.swing.JRadioButton rb4D;
    private javax.swing.JRadioButton rb5A;
    private javax.swing.JRadioButton rb5B;
    private javax.swing.JRadioButton rb5C;
    private javax.swing.JRadioButton rb5D;
    private test.PanelRound tab1;
    private test.PanelRound tab2;
    // End of variables declaration//GEN-END:variables

    private void load_data_kuis() {
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("No");
        model.addColumn("Nama");
        model.addColumn("Skor");
        try {
            int no = 1;
            String sql = "SELECT nama, skor FROM tb_data_quiz";
            java.sql.Connection conn = (Connection) Koneksi.getKoneksi();
            java.sql.Statement stm = conn.createStatement();
            java.sql.ResultSet res = stm.executeQuery(sql);
            while (res.next()){
                model.addRow(
                        new Object[]{
                            no++,
                            res.getString("nama"),
                            res.getString("skor"),
                        }
                );
            }
            TblDataKuis.setModel(model);
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }
}
