/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View;

import java.awt.Image;
import java.awt.Window;
import java.io.File;
import java.io.FileInputStream;
import java.nio.file.Files;
import java.sql.Connection;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import jnafilechooser.api.JnaFileChooser;

/**
 *
 * @author AbasZ
 */
public class MenuDaftarPermainanAdmin extends javax.swing.JPanel {

    /**
     * Creates new form MenuDaftarPermainan
     */
    public MenuDaftarPermainanAdmin() {
        initComponents();
        load_tableDaftarPermainan();
    }
    
    ImageIcon iconInvalid = new javax.swing.ImageIcon(getClass().getResource("/Img/invalid.png"));
    ImageIcon iconSucces = new javax.swing.ImageIcon(getClass().getResource("/Img/berhasil.png"));
    ImageIcon iconWarning = new javax.swing.ImageIcon(getClass().getResource("/Img/alarm.png"));

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pAlas = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TblPermainan = new javax.swing.JTable();
        pFooter = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtCariPermainan = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        BtnCariAdmin = new button.MyButton();
        jLabel4 = new javax.swing.JLabel();
        txtIdPermainan = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtNamaPermainan = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtDaerahAsal = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        BtnTambahDataPermainan = new button.MyButton();
        BtnUpdateDataPermainan = new button.MyButton();
        BtnDeleteDataPermainan = new button.MyButton();
        BtnRIsetDataPermainan = new button.MyButton();
        txtDirektori = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        taCaraBermain = new javax.swing.JTextArea();
        BtnUploadGambar = new button.MyButton();
        pTmptGambar = new javax.swing.JPanel();
        lb_Gambar = new javax.swing.JLabel();

        setLayout(new java.awt.BorderLayout());

        pAlas.setBackground(new java.awt.Color(255, 255, 204));

        TblPermainan.setBackground(new java.awt.Color(255, 255, 204));
        TblPermainan.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
        TblPermainan.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        TblPermainan.setForeground(new java.awt.Color(51, 51, 51));
        TblPermainan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "No", "ID Permainan", "Nama Permainan", "Daerah Asal", "Cara Bermain", "Gambar"
            }
        ));
        TblPermainan.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        TblPermainan.setGridColor(new java.awt.Color(51, 51, 51));
        TblPermainan.setSelectionBackground(new java.awt.Color(255, 255, 255));
        TblPermainan.setSelectionForeground(new java.awt.Color(102, 102, 102));
        TblPermainan.setShowGrid(true);
        TblPermainan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TblPermainanMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TblPermainan);
        if (TblPermainan.getColumnModel().getColumnCount() > 0) {
            TblPermainan.getColumnModel().getColumn(0).setResizable(false);
            TblPermainan.getColumnModel().getColumn(0).setPreferredWidth(5);
        }

        pFooter.setBackground(new java.awt.Color(0, 0, 153));

        jLabel3.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Copyright © by, Aperta2k24");

        javax.swing.GroupLayout pFooterLayout = new javax.swing.GroupLayout(pFooter);
        pFooter.setLayout(pFooterLayout);
        pFooterLayout.setHorizontalGroup(
            pFooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pFooterLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(263, 263, 263))
        );
        pFooterLayout.setVerticalGroup(
            pFooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pFooterLayout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addContainerGap())
        );

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setText("Data Permainan Tradisional Indonesia");

        txtCariPermainan.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        txtCariPermainan.setForeground(new java.awt.Color(102, 102, 102));
        txtCariPermainan.setText("Berdasarkan Nama Permainan");
        txtCariPermainan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtCariPermainanMouseClicked(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/search.png"))); // NOI18N

        BtnCariAdmin.setForeground(new java.awt.Color(102, 102, 102));
        BtnCariAdmin.setText("Cari");
        BtnCariAdmin.setBorderColor(new java.awt.Color(51, 51, 51));
        BtnCariAdmin.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        BtnCariAdmin.setRadius(15);
        BtnCariAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCariAdminActionPerformed(evt);
            }
        });

        jLabel4.setText("ID Permainan");

        txtIdPermainan.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        txtIdPermainan.setForeground(new java.awt.Color(102, 102, 102));

        jLabel5.setText("Nama Permainan");

        txtNamaPermainan.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        txtNamaPermainan.setForeground(new java.awt.Color(102, 102, 102));

        jLabel6.setText("Daerah Asal");

        txtDaerahAsal.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        txtDaerahAsal.setForeground(new java.awt.Color(102, 102, 102));

        jLabel7.setText("Cara Bermain");

        BtnTambahDataPermainan.setForeground(new java.awt.Color(102, 102, 102));
        BtnTambahDataPermainan.setText("Tambah");
        BtnTambahDataPermainan.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        BtnTambahDataPermainan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnTambahDataPermainanActionPerformed(evt);
            }
        });

        BtnUpdateDataPermainan.setForeground(new java.awt.Color(102, 102, 102));
        BtnUpdateDataPermainan.setText("Update");
        BtnUpdateDataPermainan.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        BtnUpdateDataPermainan.setPreferredSize(new java.awt.Dimension(73, 23));
        BtnUpdateDataPermainan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnUpdateDataPermainanActionPerformed(evt);
            }
        });

        BtnDeleteDataPermainan.setForeground(new java.awt.Color(102, 102, 102));
        BtnDeleteDataPermainan.setText("Delete");
        BtnDeleteDataPermainan.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        BtnDeleteDataPermainan.setPreferredSize(new java.awt.Dimension(73, 23));
        BtnDeleteDataPermainan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnDeleteDataPermainanActionPerformed(evt);
            }
        });

        BtnRIsetDataPermainan.setForeground(new java.awt.Color(102, 102, 102));
        BtnRIsetDataPermainan.setText("Reset");
        BtnRIsetDataPermainan.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        BtnRIsetDataPermainan.setPreferredSize(new java.awt.Dimension(73, 23));
        BtnRIsetDataPermainan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRIsetDataPermainanActionPerformed(evt);
            }
        });

        taCaraBermain.setColumns(20);
        taCaraBermain.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        taCaraBermain.setForeground(new java.awt.Color(102, 102, 102));
        taCaraBermain.setRows(5);
        jScrollPane2.setViewportView(taCaraBermain);

        BtnUploadGambar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/image.png"))); // NOI18N
        BtnUploadGambar.setBorderColor(new java.awt.Color(51, 51, 51));
        BtnUploadGambar.setRadius(10);
        BtnUploadGambar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnUploadGambarActionPerformed(evt);
            }
        });

        pTmptGambar.setBackground(new java.awt.Color(255, 255, 204));
        pTmptGambar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lb_Gambar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_Gambar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
        pTmptGambar.add(lb_Gambar, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 6, 120, 120));

        javax.swing.GroupLayout pAlasLayout = new javax.swing.GroupLayout(pAlas);
        pAlas.setLayout(pAlasLayout);
        pAlasLayout.setHorizontalGroup(
            pAlasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pAlasLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(194, 194, 194))
            .addGroup(pAlasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addComponent(pFooter, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pAlasLayout.createSequentialGroup()
                .addGroup(pAlasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pAlasLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(pAlasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(pAlasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtDaerahAsal)
                            .addComponent(txtNamaPermainan, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtIdPermainan, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 303, Short.MAX_VALUE)))
                    .addGroup(pAlasLayout.createSequentialGroup()
                        .addGap(199, 199, 199)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtCariPermainan, javax.swing.GroupLayout.DEFAULT_SIZE, 217, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pAlasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BtnTambahDataPermainan, javax.swing.GroupLayout.DEFAULT_SIZE, 77, Short.MAX_VALUE)
                    .addComponent(BtnUpdateDataPermainan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BtnDeleteDataPermainan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pAlasLayout.createSequentialGroup()
                        .addComponent(BtnCariAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(BtnRIsetDataPermainan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(15, 15, 15)
                .addGroup(pAlasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pTmptGambar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pAlasLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(txtDirektori, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(BtnUploadGambar, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(36, 36, 36))
        );
        pAlasLayout.setVerticalGroup(
            pAlasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pAlasLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pAlasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pAlasLayout.createSequentialGroup()
                        .addGroup(pAlasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCariPermainan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pAlasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel2)
                                .addComponent(BtnCariAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(21, 21, 21)
                        .addGroup(pAlasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtIdPermainan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BtnTambahDataPermainan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pAlasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNamaPermainan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(BtnUpdateDataPermainan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(9, 9, 9)
                        .addGroup(pAlasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtDaerahAsal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BtnDeleteDataPermainan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(pTmptGambar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pAlasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BtnUploadGambar, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pAlasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel7)
                        .addComponent(BtnRIsetDataPermainan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtDirektori, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addComponent(pFooter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        add(pAlas, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void TblPermainanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TblPermainanMouseClicked
        // TODO add your handling code here:
        int row = TblPermainan.getSelectedRow(); // Mendapatkan baris yang diklik

        if (row != -1) {
            // Mengisi field berdasarkan tabel
            txtIdPermainan.setText(TblPermainan.getValueAt(row, 1).toString()); // Indeks sesuai kolom id_permainan
            txtNamaPermainan.setText(TblPermainan.getValueAt(row, 2).toString()); // Indeks sesuai kolom nama_permainan
            txtDaerahAsal.setText(TblPermainan.getValueAt(row, 3).toString()); // Indeks sesuai kolom daerah_asal
            taCaraBermain.setText(TblPermainan.getValueAt(row, 4).toString()); // Indeks sesuai kolom cara_bermain

            // Ambil gambar dari database berdasarkan id_permainan
            String idPermainan = TblPermainan.getValueAt(row, 1).toString(); // Indeks sesuai kolom id_permainan
            loadGambar(idPermainan);
        }
    }

    // Fungsi untuk mengambil gambar dari database
    private void loadGambar(String idPermainan) {
        try {
            String sql = "SELECT gambar FROM tb_permainan WHERE id_permainan = ?";
            java.sql.Connection conn = (Connection) Koneksi.getKoneksi();
            java.sql.PreparedStatement pst = conn.prepareStatement(sql);
            pst.setString(1, idPermainan);

            java.sql.ResultSet rs = pst.executeQuery();
            if (rs.next()) {
                byte[] imgBytes = rs.getBytes("gambar");
                if (imgBytes != null) {
                    // Konversi byte array ke ImageIcon
                    ImageIcon imageIcon = new ImageIcon(imgBytes);

                    // Resize gambar agar sesuai JLabel
                    Image scaledImage = imageIcon.getImage().getScaledInstance(lb_Gambar.getWidth(), lb_Gambar.getHeight(), Image.SCALE_SMOOTH);
                    lb_Gambar.setIcon(new ImageIcon(scaledImage));
                } else {
                    // Kosongkan label jika tidak ada gambar
                    lb_Gambar.setIcon(null);
                    lb_Gambar.setText("Gambar tidak tersedia");
                }
            }
            rs.close();
            pst.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_TblPermainanMouseClicked

    private void BtnTambahDataPermainanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnTambahDataPermainanActionPerformed
        // TODO add your handling code here:
        if (txtNamaPermainan.getText().isEmpty() || txtDaerahAsal.getText().isEmpty() ||
                taCaraBermain.getText().isEmpty() || txtDirektori.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Tolong isi data terlebih dahulu", "Data tidak lengkap", JOptionPane.WARNING_MESSAGE, iconInvalid);
            return;
        }

        try {
            String sql = "INSERT INTO tb_permainan (nama_permainan, daerah_asal, cara_bermain, gambar) VALUES (?, ?, ?, ?)";

            java.sql.Connection conn = (Connection) Koneksi.getKoneksi();
            java.sql.PreparedStatement pst = conn.prepareStatement(sql);

            // Mengisi parameter query
            pst.setString(1, txtNamaPermainan.getText());
            pst.setString(2, txtDaerahAsal.getText());
            pst.setString(3, taCaraBermain.getText());

            // Mengubah gambar menjadi byte array
            String imagePath = txtDirektori.getText();
            if (imagePath != null && !imagePath.isEmpty()) {
                File imageFile = new File(imagePath);
                FileInputStream fis = new FileInputStream(imageFile);
                byte[] imageData = new byte[(int) imageFile.length()];
                fis.read(imageData);
                fis.close();
                pst.setBytes(4, imageData); 
            } else {
                pst.setNull(4, java.sql.Types.BLOB);
            }

            // Eksekusi query
            pst.execute();
            JOptionPane.showMessageDialog(this, "Data Berhasil Disimpan", "Success", JOptionPane.INFORMATION_MESSAGE, iconSucces);

            // Memuat ulang tabel dan mereset form
            load_tableDaftarPermainan();
            ResetTabelPermainan();
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_BtnTambahDataPermainanActionPerformed

    private void BtnUploadGambarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnUploadGambarActionPerformed
        // TODO add your handling code here:
        JnaFileChooser fileChooser = new JnaFileChooser();
        Window window = null;
        boolean action = fileChooser.showOpenDialog(window);

        if (action){
            System.out.println(fileChooser.getSelectedFile());
            File selectedFile = fileChooser.getSelectedFile();
            String path = selectedFile.getAbsolutePath();
            txtDirektori.setText(path);
            
            try {
                // Konversi blob gambar ke ImageIcon
                byte[] img = Files.readAllBytes(selectedFile.toPath());
                ImageIcon imageIcon = new ImageIcon(img);
                
                // ukuran JLabel yang diiginkan
                int labelWidth = 200;
                int labelHeight = 400;
                
                // ukuran gambar asli
                int imageWitdh = imageIcon.getIconWidth();
                int imageHeigth = imageIcon.getIconHeight();
                
                // hitung skala untuk ukuran gambar yang baru
                double scaleX = (double) labelWidth / (double) imageWitdh;
                double scaleY = (double) labelHeight / (double) imageHeigth;
                double scale = Math.min(scaleX, scaleY);
                
                // ubah ukuran gambar dengan scala yang sudah dihitung
                Image sclaedImage = imageIcon.getImage().getScaledInstance((int)(scale + imageWitdh), (int) (scale + imageHeigth),Image.SCALE_SMOOTH);
                
                // tampilkan imageIcon pada JLabel
                lb_Gambar.setIcon(new ImageIcon(sclaedImage));
                
            }catch(Exception e){
                JOptionPane.showMessageDialog(this, e.getMessage());
            }
        }
    }//GEN-LAST:event_BtnUploadGambarActionPerformed

    private void BtnUpdateDataPermainanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnUpdateDataPermainanActionPerformed
        // TODO add your handling code here:
        if (txtNamaPermainan.getText().isEmpty() || txtDaerahAsal.getText().isEmpty() || taCaraBermain.getText().isEmpty()) {
        JOptionPane.showMessageDialog(this, "Tolong isi data terlebih dahulu", "Data tidak lengkap", JOptionPane.WARNING_MESSAGE, iconInvalid);
        return;
        }

        try {
            // Logika SQL dinamis berdasarkan apakah gambar diperbarui atau tidak
            String sql;
            boolean updateGambar = txtDirektori.getText() != null && !txtDirektori.getText().isEmpty();

            if (updateGambar) {
                sql = "UPDATE tb_permainan SET nama_permainan = ?, daerah_asal = ?, cara_bermain = ?, gambar = ? WHERE id_permainan = ?";
            } else {
                sql = "UPDATE tb_permainan SET nama_permainan = ?, daerah_asal = ?, cara_bermain = ? WHERE id_permainan = ?";
            }

            java.sql.Connection conn = (Connection) Koneksi.getKoneksi();
            java.sql.PreparedStatement pst = conn.prepareStatement(sql);

            // Isi parameter
            pst.setString(1, txtNamaPermainan.getText());
            pst.setString(2, txtDaerahAsal.getText());
            pst.setString(3, taCaraBermain.getText());

            if (updateGambar) {
                // Tambahkan gambar ke query
                String imagePath = txtDirektori.getText();
                File imageFile = new File(imagePath);
                FileInputStream fis = new FileInputStream(imageFile);
                byte[] imageData = new byte[(int) imageFile.length()];
                fis.read(imageData);
                fis.close();
                pst.setBytes(4, imageData); // Parameter ke-4 untuk gambar
                pst.setString(5, txtIdPermainan.getText()); // Parameter ke-5 untuk id_permainan
            } else {
                // Gambar tidak diperbarui
                pst.setString(4, txtIdPermainan.getText()); // Parameter ke-4 untuk id_permainan
            }

            // Eksekusi query
            pst.executeUpdate();
            JOptionPane.showMessageDialog(this, "Data Berhasil Diupdate", "Success", JOptionPane.INFORMATION_MESSAGE, iconSucces);

            // Reload tabel dan reset form
            load_tableDaftarPermainan();
            ResetTabelPermainan();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_BtnUpdateDataPermainanActionPerformed

    private void BtnDeleteDataPermainanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnDeleteDataPermainanActionPerformed
        // TODO add your handling code here:
        if (txtIdPermainan.getText().isEmpty()) {
        JOptionPane.showMessageDialog(this, "Pilih data yang ingin dihapus terlebih dahulu!", "Data Tidak Terpilih", JOptionPane.WARNING_MESSAGE, iconInvalid);
        return;
        }

        // Konfirmasi penghapusan
        int confirm = JOptionPane.showConfirmDialog(this, 
                "Apakah Anda yakin ingin menghapus data ini?", 
                "Konfirmasi Hapus Data", 
                JOptionPane.YES_NO_OPTION, 
                JOptionPane.WARNING_MESSAGE,iconWarning);

        if (confirm == JOptionPane.YES_OPTION) {
            try {
                String sql;
                sql = "DELETE FROM tb_permainan WHERE id_permainan = ?";
                java.sql.Connection conn = (Connection) Koneksi.getKoneksi();
                java.sql.PreparedStatement pst = conn.prepareStatement(sql);

                // Set parameter ID yang akan dihapus
                pst.setString(1, txtIdPermainan.getText());

                // Eksekusi query
                int rowsAffected = pst.executeUpdate();
                if (rowsAffected > 0) {
                    JOptionPane.showMessageDialog(this, "Data berhasil dihapus!", "Success", JOptionPane.INFORMATION_MESSAGE, iconSucces);
                } else {
                    JOptionPane.showMessageDialog(this, "Data gagal dihapus. Pastikan ID valid!", "Error", JOptionPane.ERROR_MESSAGE, iconInvalid);
                }

                // Reload tabel dan reset form
                load_tableDaftarPermainan();
                ResetTabelPermainan();

            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Error: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_BtnDeleteDataPermainanActionPerformed

    private void BtnRIsetDataPermainanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRIsetDataPermainanActionPerformed
        // TODO add your handling code here:
        ResetTabelPermainan();
    }//GEN-LAST:event_BtnRIsetDataPermainanActionPerformed

    private void txtCariPermainanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCariPermainanMouseClicked
        // TODO add your handling code here:
        txtCariPermainan.setText("");
    }//GEN-LAST:event_txtCariPermainanMouseClicked

    private void BtnCariAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCariAdminActionPerformed
        // TODO add your handling code here:
        if (txtCariPermainan.getText().isEmpty()) {
        JOptionPane.showMessageDialog(this, "Masukkan nama permainan yang ingin dicari!", "Data Tidak Lengkap", JOptionPane.WARNING_MESSAGE, iconInvalid);
        return;
    }

        try {
            // Query SQL untuk mencari data berdasarkan nama (tidak peka huruf besar/kecil)
            String sql = "SELECT * FROM tb_permainan WHERE LOWER(nama_permainan) LIKE ?";
            java.sql.Connection conn = (Connection) Koneksi.getKoneksi();
            java.sql.PreparedStatement pst = conn.prepareStatement(sql);

            // Mengisi parameter query (mengubah input menjadi lowercase untuk pencocokan)
            pst.setString(1, "%" + txtCariPermainan.getText().toLowerCase() + "%");

            // Eksekusi query
            java.sql.ResultSet rs = pst.executeQuery();

            // Cek jika data ditemukan
            if (rs.next()) {
                // Menampilkan hasil pencarian ke field dan label gambar
                txtIdPermainan.setText(rs.getString("id_permainan"));
                txtNamaPermainan.setText(rs.getString("nama_permainan"));
                txtDaerahAsal.setText(rs.getString("daerah_asal"));
                taCaraBermain.setText(rs.getString("cara_bermain"));

                // Menampilkan gambar
                byte[] img = rs.getBytes("gambar");
                if (img != null) {
                    ImageIcon imageIcon = new ImageIcon(img);
                    Image scaledImage = imageIcon.getImage().getScaledInstance(lb_Gambar.getWidth(), lb_Gambar.getHeight(), Image.SCALE_SMOOTH);
                    lb_Gambar.setIcon(new ImageIcon(scaledImage));
                } else {
                    lb_Gambar.setIcon(null); // Kosongkan jika tidak ada gambar
                    lb_Gambar.setText("Tidak ada gambar");
                }
            } else {
                // Jika data tidak ditemukan
                JOptionPane.showMessageDialog(this, "Data tidak ditemukan!", "Hasil Pencarian", JOptionPane.INFORMATION_MESSAGE, iconWarning);

                ResetTabelPermainan();
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_BtnCariAdminActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private button.MyButton BtnCariAdmin;
    private button.MyButton BtnDeleteDataPermainan;
    private button.MyButton BtnRIsetDataPermainan;
    private button.MyButton BtnTambahDataPermainan;
    private button.MyButton BtnUpdateDataPermainan;
    private button.MyButton BtnUploadGambar;
    private javax.swing.JTable TblPermainan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lb_Gambar;
    private javax.swing.JPanel pAlas;
    private javax.swing.JPanel pFooter;
    private javax.swing.JPanel pTmptGambar;
    private javax.swing.JTextArea taCaraBermain;
    private javax.swing.JTextField txtCariPermainan;
    private javax.swing.JTextField txtDaerahAsal;
    private javax.swing.JTextField txtDirektori;
    private javax.swing.JTextField txtIdPermainan;
    private javax.swing.JTextField txtNamaPermainan;
    // End of variables declaration//GEN-END:variables

    private void load_tableDaftarPermainan() {
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("No");
        model.addColumn("ID Permainan");
        model.addColumn("Nama Permainan");
        model.addColumn("Daerah Asal");
        model.addColumn("Cara Bermain");
        try {
            int no = 1;
            String sql = "SELECT id_permainan, nama_permainan, daerah_asal, cara_bermain FROM tb_permainan";
            java.sql.Connection conn = (Connection) Koneksi.getKoneksi();
            java.sql.Statement stm = conn.createStatement();
            java.sql.ResultSet res = stm.executeQuery(sql);
            while (res.next()){
                model.addRow(
                        new Object[]{
                            no++,
                            res.getString("id_permainan"),
                            res.getString("nama_permainan"),
                            res.getString("daerah_asal"),
                            res.getString("cara_bermain"),
                        }
                );
            }
            TblPermainan.setModel(model);
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }

    private void ResetTabelPermainan() {
        txtIdPermainan.setText("");
        txtNamaPermainan.setText("");
        txtDaerahAsal.setText("");
        taCaraBermain.setText("");
        lb_Gambar.setIcon(null);
        txtDirektori.setText("");
        txtCariPermainan.setText("Berdasarkan Nama Permainan!");
    }
}
